version: '3'

services:

  voxelnet:
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        gdrive_client_id: ${gdrive_client_id} # from .env
        gdrive_client_secret: ${gdrive_client_secret} #from .env

    volumes:
      - ${LOCAL_DATA_PATH}:/data
    ports:
      - "${PORT}:${PORT}"
    #command: sh -c "dvc import https://github.com/JenWei0312/kitti.git data/train"
    
    command: sh -c "python3 train.py --alpha 1 --beta 10"
