FROM python:3.6.13

# Open CV Dependancies
RUN apt-get update 
RUN apt-get install -y \
                  ffmpeg \
                  libsm6 \
                  libxext6
# Install git                  
RUN apt-get install -y git
# Set working dir
WORKDIR /code

# Install packages
COPY requirements*.txt /code/
RUN pip3 install -r requirements.txt 

# Copy code
COPY ./src /code

# Init
RUN python3 setup.py build_ext --inplace
RUN git init 
RUN dvc init

RUN dvc import https://github.com/JenWei0312/kitti.git data/train
#RUN dvc import https://github.com/iterative/dataset-registry get-started/data.xml 